version: '3.7'

volumes:
  postgres_data:
    external: false

x-app: &app-config
  build:
    context: "."
  volumes:
    - .:/src
  restart: "unless-stopped"
  links:
    - database:database

services:
  database:
    image: postgres:13.3
    container_name: una_hora_database
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    <<: *app-config
    command: dev_web_start
    entrypoint: /src/docker-entrypoint.sh
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
    ports:
      - 8000:8000

  tailwind:
    <<: *app-config
    command: dev_tailwind_start
    entrypoint: /src/docker-entrypoint.sh
    tty: true
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    ports:
      - 8383:8383
