# Generated by Django 3.2.5 on 2021-10-12 15:37

import uuid

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        default="REQUESTED", max_length=50, verbose_name="meeting state"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, verbose_name="meeting request message"
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="meeting datetime")),
            ],
            options={
                "verbose_name": "meeting",
                "verbose_name_plural": "meetings",
                "ordering": ("-datetime",),
            },
        ),
    ]
